florist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),

    path('xml/', show_xml, name='show_xml'),
    path('html/', show_html, name='show_html'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),

    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),

    path('delete/<int:id>', delete_item, name='delete_item'),
    
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-item-ajax/', add_item_ajax, name='add_item_ajax'),
    path('delete_item_ajax/', delete_item_ajax, name='delete_item_ajax'),
    path('edit_item_ajax/', edit_item_ajax, name='edit_item_ajax'),

    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
import json
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from main.forms import ItemForm
from main.models import Item
import datetime
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods

# Create your views here.
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP D', 
        'items': items,
        'last_login': request.COOKIES['last_login'],
        'item_amount': len(items),
    }
    # return HttpResponseRedirect(reverse('main:show_main'))
    return render(request, "main.html", context)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def delete_item(request, id):
    # Get data berdasarkan ID
    item = Item.objects.get(pk = id)
    # Hapus data
    item.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def edit_item(request, id):
    # Get product berdasarkan ID
    item = Item.objects.get(pk = id)

    # Set item sebagai instance dari form
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)


def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_html(request):
    data = Item.objects.all()
    return render(request, "show_html.html", {"data" : data})

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_item_json(request):
    item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, amount=amount, description=description, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request):
    if request.method == 'DELETE':
        item_id = request.GET.get('id')
        if item_id is not None:
            try:
                item = Item.objects.get(pk=item_id)
                item.delete()
                return HttpResponse(b'DELETED', status=200)
            except Item.DoesNotExist:
                return HttpResponse(b'Item not found', status=404)
        else:
            return HttpResponse(b'Invalid request', status=400)
    else:
        return HttpResponseNotFound()

@csrf_exempt
def edit_item_ajax(request):
    if request.method == 'POST':
        item_id = request.POST.get('id')
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")

        if item_id is not None:
            try:
                item = Item.objects.get(pk=item_id, user=request.user)
                item.name = name
                item.amount = amount
                item.description = description
                item.save()
                return HttpResponse(b'UPDATED', status=200)
            except Item.DoesNotExist:
                return HttpResponse(b'Item not found', status=404)
        else:
            return HttpResponse(b'Invalid request', status=400)
    else:
        return HttpResponseNotFound()

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
    <div class="container">
        <h1 class="page-title">Add New Product</h1>

        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <input class="btn btn-primary" type="submit" value="Add Product"/>
                    </td>
                </tr>
            </table>
        </form>
    </div>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1 class="page-title">Edit Item</h1>

        <form method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <input class="btn btn-primary" type="submit" value="Save"/>
                    </td>
                </tr>
            </table>
        </form>
    </div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<div class="container">
    <div class = "login">

        <h1 class=page-title>Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn btn-primary" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Don't have an account yet? <a class="btn btn-primary" class= btn href="{% url 'main:register' %}">Register Now</a>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <h1 class="page-title">Florist Page</h1>

        <div class="user-info">
            <h5>{{name}} - {{class}}</h5>
            <!-- <h5 class="itemAmount">Amount of item in inventory: {{item_amount}}</h5> -->
            <h5 id="itemAmount"></h5>
        </div>

        <div class="contain-deck" id="itemDeck"></div>

        <div class="user-actions">
            <h5>Sesi terakhir login: {{ last_login }}</h5>

            <a type="button" class="btn btn-primary" href="{% url 'main:create_item' %}" class="btn">
                Add New Item
            </a>

            <a type="button" class="btn btn-primary" href="{% url 'main:logout' %}" class="btn">
                <img src="https://img.icons8.com/ios/50/exit--v1.png" height="24" alt="Logo" class="d-inline-block align-text-top">
                Logout
            </a>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Item by AJAX</button>
        </div>
    </div>

    <!-- Modal untuk add item -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Item</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal untuk edit -->
    <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="editModalLabel">Edit Item</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="editName" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="editAmount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="editDescription" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="editSave" data-bs-dismiss="modal">Save Item</button>
                </div>
            </div>
        </div>
    </div>

<script>
    async function getItems() {
        return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
    }

    async function refreshItems() {
        document.getElementById("itemDeck").innerHTML = ""
        const items = await getItems()
        let htmlString = ""
        items.forEach((item,index) => {
            const last = index === items.length -1;
            htmlString += `<div class="${last ? 'bg-last' : 'card-container'}">
                <div class="card-body">
                    <h5 class="card-title">${item.fields.name}</h5>
                    <p class="card-text">Amount: ${item.fields.amount}</p>
                    <p class="card-text">Description: </p>
                    <p class="card-text">${item.fields.description} </p>
                    <p class="card-text">Date Added: ${item.fields.date_added}</p>
                    <button type="button" class="btn btn-danger" style="position:absolute; bottom: 10px" onclick="deleteItem(${item.pk})">
                        <img width="15" height="auto" src="https://img.icons8.com/ios-glyphs/30/filled-trash.png" alt="Delete"></img>
                    </button>
                    <button type="button" class="btn btn-primary" style="position:absolute; left:55px; bottom: 10px" data-bs-toggle="modal" data-bs-target="#editModal" onclick="editItem(${item.pk})">
                        <img width="15" height="auto" src="https://img.icons8.com/material-outlined/24/edit--v1.png" alt="Edit"></img>
                    </button>
                </div>
            </div>` 
        })
        
        document.getElementById("itemDeck").innerHTML = htmlString
    }

    async function refreshItemAmount() {
        document.getElementById("itemAmount").innerHTML = "";
        const items = await getItems();
        let itemAmount = 0;
        items.forEach((item) => {
            itemAmount += 1;
        });

        let htmlString = `<h5>Amount of item in inventory: ${itemAmount}</h5>`;
        document.getElementById("itemAmount").innerHTML = htmlString;
    }

    async function deleteItem(itemId) {
        await fetch(`{% url 'main:delete_item_ajax' %}?id=${itemId}`, {
            method: "DELETE",
        })
        refreshItems();
        refreshItemAmount();
    }
    refreshItems();
    refreshItemAmount();

    async function editItem(itemId) {
    // Get the item details
    const item = (await getItems()).find((item) => item.pk === itemId);

    // Populate a form or modal with the item details
    document.getElementById('editName').value = item.fields.name;
    document.getElementById('editAmount').value = item.fields.amount;
    document.getElementById('editDescription').value = item.fields.description;

    // Show the form or modal
    document.getElementById('editModal').style.display = 'block';

        // Attach an event listener to the submit button
        document.getElementById('editSave').onclick = async function() {
            // Get the updated details from the form
            const name = document.getElementById('editName').value;
            const amount = document.getElementById('editAmount').value;
            const description = document.getElementById('editDescription').value;

            // Send a POST request to the server to update the item
            const formData = new FormData();
            formData.append('id', itemId);
            formData.append('name', name);
            formData.append('amount', amount);
            formData.append('description', description);
            await fetch("{% url 'main:edit_item_ajax' %}", {
                method: "POST",
                body: formData,
            });

            // Hide the form or modal and refresh the items
            document.getElementById('editModal').style.display = 'none';
            refreshItems();
            refreshItemAmount();
        };
    }


    function addItem() {
        fetch("{% url 'main:add_item_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems).then(refreshItemAmount)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addItem
</script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
<div class="container">
    <div class = "login">
        
        <h1 class="page-title">Register</h1>  

            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input class="btn btn-primary" type="submit" name="submit" value="Register"/></td>  
                    </tr>  
                </table>  
            </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}
    </div>
</div>  

{% endblock content %}

main/templates/show_html.html
{% extends 'base.html' %}

{% block content %}
    <h1>Shopping List Page</h1>
    
    <table>
        <tr>
            <th>Name</th>
            <th>Amount</th>
            <th>Description</th>
            <th>Date Added</th>
        </tr>

        {% comment %} Below is how to show the item data {% endcomment %}

        {% for item in data %}
            <tr>
                <td>{{item.name}}</td>
                <td>{{item.amount}}</td>
                <td>{{item.description}}</td>
                <td>{{item.date_added}}</td>
            </tr>
        {% endfor %}
    </table>

    <br />

    <a href="{% url 'main:create_item' %}">
        <button>
            Add New Product
        </button>
    </a>

{% endblock content %}